#用yml文件的格式书写配置文件
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: xyz.jpsoswer.mybatis.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名开关
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tials
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jss0219

  #设置文件的传输限制
  servlet:
    multipart:
      #单次传输文件大小
      max-file-size: 10MB
      #单次请求传输大小
      max-request-size: 100MB

#连接数据库所需要的配置

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
