#用yml文件的格式书写配置文件
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: xyz.jpsoswer.mybatis.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web01
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jss0219

#连接数据库所需要的配置